In [1]:
import numpy as np
from numpy import genfromtxt


In [2]:
data = genfromtxt('Computer-Vision-with-Python/Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
len(X_train)

919

In [14]:
len(X)

1372

In [15]:
len(X_test)

453

In [16]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_obj = MinMaxScaler()

In [19]:
scaler_obj.fit( X_train )

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train = scaler_obj.transform(X_train)

In [21]:
scaled_X_test = scaler_obj.transform(X_test)

In [22]:
scaled_X_train.max()

1.0000000000000002

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [26]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [27]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.7091 - acc: 0.4516
Epoch 2/50
 - 0s - loss: 0.6851 - acc: 0.4679
Epoch 3/50
 - 0s - loss: 0.6638 - acc: 0.7084
Epoch 4/50
 - 0s - loss: 0.6476 - acc: 0.7628
Epoch 5/50
 - 0s - loss: 0.6351 - acc: 0.7954
Epoch 6/50
 - 0s - loss: 0.6225 - acc: 0.8259
Epoch 7/50
 - 0s - loss: 0.6081 - acc: 0.8368
Epoch 8/50
 - 0s - loss: 0.5926 - acc: 0.8455
Epoch 9/50
 - 0s - loss: 0.5754 - acc: 0.8520
Epoch 10/50
 - 0s - loss: 0.5576 - acc: 0.8542
Epoch 11/50
 - 0s - loss: 0.5392 - acc: 0.8553
Epoch 12/50
 - 0s - loss: 0.5204 - acc: 0.8564
Epoch 13/50
 - 0s - loss: 0.5018 - acc: 0.8651
Epoch 14/50
 - 0s - loss: 0.4836 - acc: 0.8727
Epoch 15/50
 - 0s - loss: 0.4662 - acc: 0.8716
Epoch 16/50
 - 0s - loss: 0.4497 - acc: 0.8770
Epoch 17/50
 - 0s - loss: 0.4340 - acc: 0.8792
Epoch 18/50
 - 0s - loss: 0.4194 - acc: 0.8792
Epoch 19/50
 - 0s - loss: 0.4053 - acc: 0.8814
Epoch 20/50
 - 0s - loss: 0.3924 - acc: 0.8868
Epoch 21/50
 - 0s - loss: 0.3793 - acc: 0.8901
Epoch 22/50
 - 0s - lo

In [29]:
#model.predict_classes(scaled_X_test)

In [30]:
model.metrics_names

['loss', 'acc']

In [31]:
from sklearn.metrics import confusion_matrix,classification_report

In [32]:
predictions = model.predict_classes(scaled_X_test)

In [33]:
confusion_matrix(y_test,predictions)

array([[252,   5],
       [ 19, 177]], dtype=int64)

In [34]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.93      0.98      0.95       257
        1.0       0.97      0.90      0.94       196

avg / total       0.95      0.95      0.95       453



In [35]:
model.save('myModel.h5')

In [36]:
from keras.models import load_model

In [37]:
newModel = load_model('myModel.h5')

In [38]:
newModel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    